blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/kanutocd/rack_jwt_aegis/blob/main/README.md
    about: Check the documentation for usage examples and configuration options
  - name: Security Issues
    url: https://github.com/kanutocd/rack_jwt_aegis/security/advisories/new
    about: Please report security vulnerabilities privately through GitHub Security Advisories