name: Feature Request
description: Suggest an idea for rack_jwt_aegis
title: "[Feature]: "
labels: ["enhancement", "triage"]
assignees: [kanutocd]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature!

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Category
      description: What category does this feature belong to?
      options:
        - JWT Authentication
        - Multi-tenant Support
        - RBAC/Authorization
        - Caching
        - Configuration
        - Performance
        - Security
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your specific use case and how this feature would help.
      placeholder: |
        In my application, I need to...
        This feature would allow me to...

  - type: textarea
    id: example
    attributes:
      label: Example Usage
      description: If applicable, provide an example of how this feature might be used.
      render: ruby
      placeholder: |
        # Example configuration or usage
        use RackJwtAegis::Middleware, {
          new_feature: true,
          new_option: 'value'
        }

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/kanutocd/rack_jwt_aegis/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
